#!/bin/bash

# /etc/init.d/prometheusnginx
#
# Startup script for prometheusnginx
#
# chkconfig: 2345 20 80
# description: Starts and stops etcdkeeper

. /etc/init.d/functions

prog="prometheus-nginxlog-exporter"
prog_bin="/data/prometheusNginx/$prog"
desc="prometheusnginx service discovery daemon"

USER="prometheus"
OPTS="-config-file /data/prometheusNginx/config.yaml"
OUT_FILE="/var/log/prometheusNginx.log"


if ! [ -f $prog_bin ]; then
  echo "$prog binary not found."
  exit 5
fi

#if [ -f /etc/sysconfig/$prog ]; then
#  . /etc/sysconfig/$prog
#else
#  echo "No sysconfig file found in /etc/sysconfig/$prog... exiting."
#  exit 5
#fi

start() {
  echo "Starting $desc ($prog): "
  su $USER -c "nohup $prog_bin $OPTS >> $OUT_FILE 2>&1 &"
  RETVAL=$?
  return $RETVAL
}

stop() {
  echo "Shutting down $desc ($prog): "
  pkill -f $prog_bin
}

restart() {
    stop
    start
}

status() {
  if [ -z $pid ]; then
     pid=$(pgrep -f $prog_bin)
  fi

  if [ -z $pid ]; then
    echo "$prog is NOT running."
    return 1
  else
    echo "$prog is running (pid is $pid)."
  fi

}

case "$1" in
  start)   start;;
  stop)    stop;;
  restart) restart;;
  status)  status;;
  *)       echo "Usage: $0 {start|stop|restart|status}"
           RETVAL=2;;
esac
exit $RETVAL
